DROP TABLE IF EXISTS tasks;

CREATE TABLE tasks(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	task_text TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	due_at TIMESTAMP NOT NULL,
	progress INT NOT NULL DEFAULT 0
);